name: Cleanup Old Images

on:
  workflow_dispatch:
    inputs:
      num_to_keep:
        description: 'Number of recent versions to keep'
        required: true
        default: '5'
  schedule:
    - cron: '0 0 * * 0' # Weekly cleanup

permissions: {}

jobs:
  delete-versions:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      packages: write
    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: 'resolix'
          package-type: 'container'
          min-versions-to-keep: ${{ github.event.inputs.num_to_keep || 5 }}
          delete-only-untagged-versions: 'false'
